### ISSUE TITLE
Proximity should use mouseover instead of mousemove

### ISSUE THREAD

**Issue by JamieLivingstone** [MikeDigitize/lazy#9]
Currently the Lazy Proximity is using mouseover. So if I was to scroll rather than hover over the target element, my mousemove event will not be triggered as I haven't touched my mouse even though my cursor is on the target element in the browser.

By changing the proximity to use mouseover it would resolve the issue.

**Comment by MikeDigitize** [comment]
Good shout - [pushed a change](https://github.com/MikeDigitize/lazy/commit/ed8d7688100d5c9faa6b5e9e9d6249f56fe9c163)
